=== cimbriano/pennphoto17/Milestone1/pennphoto17.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="pennphoto17ns"
	xmlns:tns="pennphoto17ns" elementFormDefault="qualified" >
	
	<element name="photodb" type="tns:photodbType">
		<key name="userId">
			<selector xpath="user" />
			<field xpath="id" />
		</key>
		<keyref name="circleUserRef" refer="tns:userId">
					<selector xpath="user/circle" />
					<field xpath="friend_id" />
			</keyref>
	</element>
	
	<complexType name="photodbType">
		<sequence>
			<element ref="tns:user" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
	</complexType>

	<element name="user" type="tns:userType"></element>
	<element name="student" type="tns:studentType" substitutionGroup="tns:user"></element>
	<element name="professor" type="tns:professorType" substitutionGroup="tns:user"></element>

	<complexType name="userType">
		<sequence>
			<element name="id" type="int"></element>
			<element name="email" type="string"></element>
			<element name="first_name" type="string"></element>
			<element name="last_name" type="string"></element>
			<element name="dob" type="date"></element>
			<element name="street_address" type="string"></element>
			<element name="city" type="string"></element>
			<element name="state" type="string"></element>
			<element name="zip_code" type="string"></element>
			<element name="is_professor" type="boolean"></element>
			<element name="gender" type="string"></element>

			<element name="interest" type="string"
				maxOccurs="unbounded" minOccurs="0">
			</element>

			<element name="attended" type="tns:attendedType"
				maxOccurs="unbounded" minOccurs="0">
			</element>

			<element name="photo" type="tns:photoType" maxOccurs="unbounded"
				minOccurs="0">
			</element>

			<element name="circle" type="tns:circleType" maxOccurs="unbounded"
				minOccurs="0">
				
			</element>
		</sequence>
	</complexType>

	<complexType name="studentType">
		<complexContent>
			<extension base="tns:userType">
				<sequence>
					<element name="major" type="string"></element>
					<element name="GPA" type="float"></element>
					<element name="advisor_id" type="int"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="professorType">
		<complexContent>
			<extension base="tns:userType">
				<sequence>
					<element name="researchArea" type="string"></element>
					<element name="title" type="string"></element>
					<sequence maxOccurs="unbounded" minOccurs="0">
						<element name="advisee_id" type="int"></element>
					</sequence>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="attendedType">
		<sequence>
			<element name="name" type="string"></element>
			<element name="start_year" type="int"></element>
			<element name="end_year" type="int"></element>
		</sequence>
	</complexType>

	<complexType name="photoType">
		<sequence>
			<element name="id" type="int"></element>
			<element name="url" type="string"></element>
			<element name="is_private" type="boolean"></element>
			<element name="upload_date" type="dateTime"></element>			

			<element name="rating" type="tns:ratingType" maxOccurs="unbounded"
				minOccurs="0">
			</element>

			<element name="tag" type="tns:tagType" maxOccurs="unbounded"
				minOccurs="0"></element>
                        
                        <element name="visible_to" type="tns:visibleToType" maxOccurs="1"
                                minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="ratingType">
		<sequence>
			<element name="user_id" type="int"></element>
			<element name="value" type="int"></element>
		</sequence>
	</complexType>
	
		<complexType name="tagType">
		<sequence>
			<element name="user_id" type="int"></element>
			<element name="tag_text" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="circleType">
		<sequence>
			<element name="name" type="string"></element>
			<element name="friend_id" type="int" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
	</complexType>

  <complexType name="visibleToType">
    <sequence>
	    <element name="circle_id" type="int" maxOccurs="unbounded"
	            minOccurs="0"></element>                        
	    <element name="user_id" type="int" maxOccurs="unbounded"
	            minOccurs="0"></element>
    </sequence>
  </complexType>
</schema>

=== cimbriano/pennphoto17/Milestone2/pennphoto17data.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:photodb xmlns:tns="pennphoto17ns"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="pennphoto17ns pennphoto17.xsd ">

	<tns:professor>
		<tns:id>17001</tns:id>
		<tns:email>Randy@penn.edu</tns:email>
		<tns:first_name>Randolph</tns:first_name>
		<tns:last_name>Duke</tns:last_name>
		<tns:dob>1904-06-17</tns:dob>
		<tns:street_address>135 South Broad Street</tns:street_address>
		<tns:city>Philadelphia</tns:city>
		<tns:state>PA</tns:state>
		<tns:zip_code>19103</tns:zip_code>
		<tns:is_professor>true</tns:is_professor>
		<tns:gender>m</tns:gender>
		<tns:interest>High Finance</tns:interest>
		<tns:interest>Developmental Studies</tns:interest>
		<tns:photo>
			<tns:id>17101</tns:id>
			<tns:url>https://encrypted-tbn1.google.com/images?q=tbn:ANd9GcT049o2sVTxKrCwv5CQdtEHptn4i5w4fmcq-BCtxI66ltHV-uaDEQ</tns:url>
			<tns:is_private>false</tns:is_private>
			<tns:upload_date>2001-12-31T12:00:00</tns:upload_date>
			<tns:rating>
				<tns:user_id>17001</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17002</tns:user_id>
				<tns:value>3</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17003</tns:user_id>
				<tns:value>1</tns:value>
			</tns:rating>
			<tns:tag>
				<tns:user_id>17003</tns:user_id>
				<tns:tag_text>Scrooge</tns:tag_text>
			</tns:tag>
			<tns:tag>
				<tns:user_id>17002</tns:user_id>
				<tns:tag_text>Fool</tns:tag_text>
			</tns:tag>
		</tns:photo>
		<tns:photo>
			<tns:id>17201</tns:id>
			<tns:url>http://www.crossingwallstreet.com/Trading-Places--C10045389.jpeg</tns:url>
			<tns:is_private>true</tns:is_private>
			<tns:upload_date>2001-12-31T12:00:00</tns:upload_date>
			<tns:rating>
				<tns:user_id>17002</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:tag>
				<tns:user_id>17002</tns:user_id>
				<tns:tag_text>Dukes rule!</tns:tag_text>
			</tns:tag>
			<tns:visible_to>
				<tns:circle_id>170011</tns:circle_id>
			</tns:visible_to>
		</tns:photo>
		<tns:circle>
			<tns:id>17101</tns:id>
			<tns:name>Family</tns:name>
			<tns:friend_id>17002</tns:friend_id>
		</tns:circle>
		<tns:circle>
			<tns:id>17201</tns:id>
			<tns:name>Employees</tns:name>
			<tns:friend_id>17003</tns:friend_id>
			<tns:friend_id>17004</tns:friend_id>
			<tns:friend_id>17005</tns:friend_id>
		</tns:circle>
		<tns:researchArea>Social Policy</tns:researchArea>
		<tns:title>Partner</tns:title>
	</tns:professor>
	<tns:professor>
		<tns:id>17002</tns:id>
		<tns:email>morty@penn.edu</tns:email>
		<tns:first_name>Mortimer</tns:first_name>
		<tns:last_name>Duke</tns:last_name>
		<tns:dob>1908-05-31</tns:dob>
		<tns:street_address>135 South Broad Street</tns:street_address>
		<tns:city>Philadelphia</tns:city>
		<tns:state>PA</tns:state>
		<tns:zip_code>19103</tns:zip_code>
		<tns:is_professor>true</tns:is_professor>
		<tns:gender>m</tns:gender>
		<tns:interest>Insider Trading</tns:interest>
		<tns:interest>Gambling</tns:interest>
		<tns:photo>
			<tns:id>17102</tns:id>
			<tns:url>http://www.wearysloth.com/Gallery/ActorsA/305-19933.gif</tns:url>
			<tns:is_private>false</tns:is_private>
			<tns:upload_date>2011-10-31T12:00:00</tns:upload_date>
			<tns:rating>
				<tns:user_id>17001</tns:user_id>
				<tns:value>3</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17002</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17005</tns:user_id>
				<tns:value>1</tns:value>
			</tns:rating>
			<tns:tag>
				<tns:user_id>17001</tns:user_id>
				<tns:tag_text>Boring</tns:tag_text>
			</tns:tag>
			<tns:tag>
				<tns:user_id>17002</tns:user_id>
				<tns:tag_text>Old</tns:tag_text>
			</tns:tag>
		</tns:photo>
		<tns:photo>
			<tns:id>17202</tns:id>
			<tns:url>http://1.bp.blogspot.com/_VlmHNP9So5Y/SbZxlhVqJcI/AAAAAAAABAE/6ioKA-wkmns/s400/TradingPlaces_4.jpg</tns:url>
			<tns:is_private>false</tns:is_private>
			<tns:upload_date>2001-12-31T12:00:00</tns:upload_date>
			<tns:rating>
				<tns:user_id>17001</tns:user_id>
				<tns:value>1</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17004</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:tag>
				<tns:user_id>17004</tns:user_id>
				<tns:tag_text>Good times!</tns:tag_text>
			</tns:tag>
		</tns:photo>
		<tns:circle>
			<tns:id>17102</tns:id>
			<tns:name>Family</tns:name>
			<tns:friend_id>17002</tns:friend_id>
		</tns:circle>
		<tns:circle>
			<tns:id>17202</tns:id>
			<tns:name>Riff Raff</tns:name>
			<tns:friend_id>17003</tns:friend_id>
			<tns:friend_id>17007</tns:friend_id>
			<tns:friend_id>17009</tns:friend_id>
		</tns:circle>
		<tns:researchArea>Agriculture</tns:researchArea>
		<tns:title>Partner</tns:title>
	</tns:professor>
	<tns:student>
		<tns:id>17003</tns:id>
		<tns:email>capricorn@penn.edu</tns:email>
		<tns:first_name>Billy Ray</tns:first_name>
		<tns:last_name>Valentine</tns:last_name>
		<tns:dob>1961-04-03</tns:dob>
		<tns:street_address>Rittenhouse Square</tns:street_address>
		<tns:city>Philadelphia</tns:city>
		<tns:state>PA</tns:state>
		<tns:zip_code>19103</tns:zip_code>
		<tns:is_professor>false</tns:is_professor>
		<tns:gender>m</tns:gender>
		<tns:interest>Frozen Concentrated Orange Juice</tns:interest>
		<tns:interest>Pork Bellies</tns:interest>
		<tns:attended>
			<tns:name>School of Hard Knocks</tns:name>
			<tns:start_year>2009</tns:start_year>
			<tns:end_year>2013</tns:end_year>
		</tns:attended>
		<tns:photo>
			<tns:id>17103</tns:id>
			<tns:url>http://mimg.ugo.com/201012/7/3/9/160937/cuts/trading_480x480.jpg</tns:url>
			<tns:is_private>false</tns:is_private>
			<tns:upload_date>2001-12-31T12:00:00</tns:upload_date>
			<tns:rating>
				<tns:user_id>17003</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17001</tns:user_id>
				<tns:value>1</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17002</tns:user_id>
				<tns:value>2</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17007</tns:user_id>
				<tns:value>4</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17011</tns:user_id>
				<tns:value>4</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17014</tns:user_id>
				<tns:value>2</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17017</tns:user_id>
				<tns:value>3</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17020</tns:user_id>
				<tns:value>4</tns:value>
			</tns:rating>
		</tns:photo>
		<tns:photo>
			<tns:id>17203</tns:id>
			<tns:url>http://img.photobucket.com/albums/v130/GaryWGraley/misc/tradingPlaces.jpg</tns:url>
			<tns:is_private>false</tns:is_private>
			<tns:upload_date>2001-12-31T12:00:00</tns:upload_date>
			<tns:rating>
				<tns:user_id>17003</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17004</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17005</tns:user_id>
				<tns:value>3</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17002</tns:user_id>
				<tns:value>1</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17001</tns:user_id>
				<tns:value>1</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17011</tns:user_id>
				<tns:value>2</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17012</tns:user_id>
				<tns:value>3</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17013</tns:user_id>
				<tns:value>4</tns:value>
			</tns:rating>
			<tns:tag>
				<tns:user_id>17006</tns:user_id>
				<tns:tag_text>Big fun</tns:tag_text>
			</tns:tag>
			<tns:tag>
				<tns:user_id>17008</tns:user_id>
				<tns:tag_text>Train</tns:tag_text>
			</tns:tag>
			<tns:tag>
				<tns:user_id>17011</tns:user_id>
				<tns:tag_text>Party</tns:tag_text>
			</tns:tag>
			<tns:tag>
				<tns:user_id>17019</tns:user_id>
				<tns:tag_text>Costumes</tns:tag_text>
			</tns:tag>
		</tns:photo>
		<tns:circle>
			<tns:id>17103</tns:id>
			<tns:name>People Who Jacuzzi</tns:name>
			<tns:friend_id>17001</tns:friend_id>
			<tns:friend_id>17002</tns:friend_id>
			<tns:friend_id>17004</tns:friend_id>
		</tns:circle>
		<tns:circle>
			<tns:id>17203</tns:id>
			<tns:name>Jive Turkeys</tns:name>
			<tns:friend_id>17007</tns:friend_id>
			<tns:friend_id>17012</tns:friend_id>
			<tns:friend_id>17014</tns:friend_id>
		</tns:circle>
		<tns:circle>
			<tns:id>17303</tns:id>
			<tns:name>African Education Conference</tns:name>
			<tns:friend_id>17006</tns:friend_id>
			<tns:friend_id>17017</tns:friend_id>
			<tns:friend_id>17019</tns:friend_id>
		</tns:circle>
		<tns:major>Comeuppance</tns:major>
		<tns:gpa>3.8</tns:gpa>
		<tns:advisor_id>17001</tns:advisor_id>
	</tns:student>
	<tns:student>
		<tns:id>17004</tns:id>
		<tns:email>louis@penn.edu</tns:email>
		<tns:first_name>Louis</tns:first_name>
		<tns:last_name>Winthorpe</tns:last_name>
		<tns:dob>1952-07-01</tns:dob>
		<tns:street_address>2014 Delancy Street</tns:street_address>
		<tns:city>Philadelphia</tns:city>
		<tns:state>PA</tns:state>
		<tns:zip_code>19103</tns:zip_code>
		<tns:is_professor>false</tns:is_professor>
		<tns:gender>m</tns:gender>
		<tns:interest>Revenge</tns:interest>
		<tns:interest>Escorts with a heart of gold</tns:interest>
		<tns:attended>
			<tns:name>Harvard Business School</tns:name>
			<tns:start_year>2009</tns:start_year>
			<tns:end_year>2011</tns:end_year>
		</tns:attended>
		<tns:attended>
			<tns:name>Harvard</tns:name>
			<tns:start_year>2000</tns:start_year>
			<tns:end_year>2004</tns:end_year>
		</tns:attended>
		<tns:photo>
			<tns:id>17104</tns:id>
			<tns:url>http://farm4.staticflickr.com/3163/2943716236_5860cb99e0_m.jpg</tns:url>
			<tns:is_private>false</tns:is_private>
			<tns:upload_date>2008-11-25T12:00:00</tns:upload_date>
			<tns:rating>
				<tns:user_id>17003</tns:user_id>
				<tns:value>5</tns:value>
			</tns:rating>
			<tns:rating>
				<tns:user_id>17001</tns:user_id>
				<tns:value>4</tns:value>
